# Generated by Django 4.1.7 on 2023-03-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('todo', '0006_todo_completed_todo_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='user.user'),
            preserve_default=False,
        ),
    ]
