# Generated by Django 4.1.7 on 2023-03-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_id',
        ),
    ]
