# Generated by Django 4.1.7 on 2023-07-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_user_id_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
