# Generated by Django 4.1.7 on 2023-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_todo_completed_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='New', max_length=20),
        ),
    ]
